Repository stabilitydao/stability-contracts, pull requests merged in 2023-11, with the labels that each got.

#17 AI audit
  .github/workflows/slither.yml
  audits/InitialAuditReport.md
  audits/README.md
  slither.config.json
Labels: ALPHA

#15 Minimal docs
  .github/workflows/test.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/AprOracle.sol
  src/core/CVault.sol
  src/core/Factory.sol
  src/core/HardWorker.sol
  src/core/Platform.sol
  src/core/PriceReader.sol
  src/core/RMVault.sol
  src/core/RVault.sol
  src/core/StrategyLogic.sol
  src/core/Swapper.sol
  src/core/VaultManager.sol
  src/core/base/Controllable.sol
  src/core/base/RVaultBase.sol
  src/core/base/UpgradeableProxy.sol
  src/core/base/VaultBase.sol
  src/core/proxy/Proxy.sol
  src/interfaces/IAprOracle.sol
  src/interfaces/IControllable.sol
  src/interfaces/IDexAdapter.sol
  src/interfaces/IFactory.sol
  src/interfaces/IFarmingStrategy.sol
  src/interfaces/IHardWorker.sol
  src/interfaces/IManagedVault.sol
  src/interfaces/IOracleAdapter.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IPriceReader.sol
  src/interfaces/IProxy.sol
  src/interfaces/IRVault.sol
  src/interfaces/IStrategy.sol
  src/interfaces/IStrategyLogic.sol
  src/interfaces/IStrategyProxy.sol
  src/interfaces/ISwapper.sol
  src/interfaces/IVault.sol
  src/interfaces/IVaultManager.sol
  src/interfaces/IVaultProxy.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/README.md
  src/strategies/base/FarmingStrategyBase.sol
  src/test/MockDexAdapter.sol
Labels: documentation, ALPHA

#11 Coverage of functions
  .gitignore
  src/core/libs/FactoryLib.sol
  src/interfaces/IRVault.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/UniswapV3MathLib.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/RMVault.Polygon.t.sol
  test/core/Vault.t.sol
  test/core/VaultManager.t.sol
Labels: ALPHA

#19 Add Events
  src/core/AprOracle.sol
  src/core/Factory.sol
  src/core/Platform.sol
  src/core/PriceReader.sol
  src/core/StrategyLogic.sol
  src/core/Swapper.sol
  src/core/VaultManager.sol
  src/interfaces/IAprOracle.sol
  src/interfaces/IFactory.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IPriceReader.sol
  src/interfaces/IStrategyLogic.sol
  src/interfaces/ISwapper.sol
  src/interfaces/IVaultManager.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/StrategyLib.sol
Labels: ALPHA

#18 Slither: High severity alerts, partially the rest.
  slither.config.json
  src/adapters/AlgebraAdapter.sol
  src/adapters/ChainlinkAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/Factory.sol
  src/core/HardWorker.sol
  src/core/Platform.sol
  src/core/PriceReader.sol
  src/core/RMVault.sol
  src/core/Swapper.sol
  src/core/VaultManager.sol
  src/core/base/UpgradeableProxy.sol
  src/core/base/VaultBase.sol
  src/core/libs/FactoryLib.sol
  src/core/proxy/StrategyProxy.sol
  src/core/proxy/VaultProxy.sol
  src/integrations/algebra/IAlgebraPool.sol
  src/integrations/algebra/IDataStorageOperator.sol
  src/integrations/algebra/pool/IAlgebraPoolActions.sol
  src/integrations/algebra/pool/IAlgebraPoolDerivedState.sol
  src/integrations/algebra/pool/IAlgebraPoolEvents.sol
  src/integrations/algebra/pool/IAlgebraPoolImmutables.sol
  src/integrations/algebra/pool/IAlgebraPoolPermissionedActions.sol
  src/integrations/algebra/pool/IAlgebraPoolState.sol
  src/integrations/kyber/IBasePositionManager.sol
  src/integrations/kyber/IFactory.sol
  src/integrations/kyber/IKyberQuoterV2.sol
  src/integrations/kyber/IKyberSwapElasticLM.sol
  src/integrations/kyber/IPool.sol
  src/integrations/kyber/IRouterTokenHelper.sol
  src/integrations/kyber/ITicksFeesReader.sol
  src/integrations/kyber/base_position_manager/IBasePositionManagerEvents.sol
  src/integrations/kyber/oracle/IPoolOracle.sol
  src/integrations/kyber/pool/IPoolStorage.sol
  src/integrations/uniswapv3/IUniswapV3Factory.sol
  src/integrations/uniswapv3/IUniswapV3Pool.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolActions.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolDerivedState.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolEvents.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolImmutables.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolOwnerActions.sol
  src/integrations/uniswapv3/pool/IUniswapV3PoolState.sol
  src/interfaces/IFactory.sol
  src/interfaces/IHardWorker.sol
  src/interfaces/IPlatform.sol
  src/interfaces/ISwapper.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/StrategyLib.sol
  test/core/Platform.Polygon.t.sol
  test/core/Platform.t.sol
  test/core/Swapper.Polygon.t.sol
Labels: ALPHA, refactoring

#24 Refactoring: vaults folder, strategies codebase
  script/libs/DeployLib.sol
  src/adapters/ChainlinkAdapter.sol
  src/core/Platform.sol
  src/core/StrategyLogic.sol
  src/core/vaults/CVault.sol
  src/core/vaults/RMVault.sol
  src/core/vaults/RVault.sol
  src/interfaces/IControllable.sol
  src/interfaces/IPairStrategyBase.sol
  src/interfaces/IStrategy.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/FarmingStrategyBase.sol
  src/strategies/base/PairStrategyBase.sol
  src/strategies/base/StrategyBase.sol
  src/test/MockStrategy.sol
  src/test/MockVaultUpgrade.sol
  test/base/FullMockSetup.sol
  test/base/MockSetup.sol
  test/base/UniversalTest.sol
  test/base/chains/PolygonSetup.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/Proxy.t.sol
  test/core/Vault.t.sol
  test/core/VaultManager.t.sol
Labels: ALPHA, refactoring

#27 semgrep: setup rules
  .github/workflows/semgrep.yml
Labels: ALPHA, SECURITY

#21 Full Coverage: Platform, improvement on other contracts
  src/core/Platform.sol
  src/interfaces/IHardWorker.sol
  src/interfaces/IPlatform.sol
  test/base/MockSetup.sol
  test/base/UniversalTest.sol
  test/core/Platform.Polygon.t.sol
  test/core/Platform.t.sol
  test/core/PriceReader.t.sol
Labels: ALPHA

#23 DeX aggregators, AMM adapter getProportions, ILPStrategy + LPStrategyBase, ZAP deposit, improve universal test, fixes
  chains/PolygonLib.sol
  script/libs/DeployLib.sol
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/Platform.sol
  src/core/Zap.sol
  src/core/base/VaultBase.sol
  src/core/libs/FactoryLib.sol
  src/core/proxy/Proxy.sol
  src/interfaces/IDexAdapter.sol
  src/interfaces/ILPStrategy.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IZap.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/README.md
  src/strategies/base/LPStrategyBase.sol
  src/strategies/libs/LPStrategyLib.sol
  src/strategies/libs/StrategyLib.sol
  src/test/MockDexAdapter.sol
  src/test/MockStrategy.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/adapters/KyberAdapter.Polygon.t.sol
  test/adapters/UniswapV3Adapter.Polygon.t.sol
  test/base/FullMockSetup.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/VaultManager.t.sol
  test/core/Zap.Polygon.t.sol
Labels: enhancement, ALPHA, refactoring

#31 DeX adapter -> AMM adapter
  chains/PolygonLib.sol
  script/libs/DeployAdapterLib.sol
  script/libs/DeployLib.sol
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/adapters/libs/AmmAdapterIdLib.sol
  src/core/Platform.sol
  src/core/Swapper.sol
  src/interfaces/IAmmAdapter.sol
  src/interfaces/ILPStrategy.sol
  src/interfaces/IPlatform.sol
  src/interfaces/ISwapper.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/README.md
  src/strategies/base/LPStrategyBase.sol
  src/strategies/libs/LPStrategyLib.sol
  src/strategies/libs/QuickswapLib.sol
  src/test/MockAmmAdapter.sol
  src/test/MockStrategy.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/adapters/KyberAdapter.Polygon.t.sol
  test/adapters/UniswapV3Adapter.Polygon.t.sol
  test/base/FullMockSetup.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/Swapper.Polygon.t.sol
  test/core/Vault.t.sol
Labels: ALPHA, refactoring

#35 ERC-165: Standard Interface Detection
  src/core/Factory.sol
  src/core/Platform.sol
  src/core/README.md
  src/core/StrategyLogic.sol
  src/core/VaultManager.sol
  src/core/base/Controllable.sol
  src/core/base/RVaultBase.sol
  src/core/base/VaultBase.sol
  src/interfaces/IFactory.sol
  src/interfaces/IStrategy.sol
  src/interfaces/IVault.sol
  src/interfaces/IVaultManager.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/FarmingStrategyBase.sol
  src/strategies/base/LPStrategyBase.sol
  src/strategies/base/StrategyBase.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.Polygon.t.sol
  test/core/Platform.t.sol
  test/core/VaultManager.t.sol
Labels: enhancement, ALPHA

#33 Namespaced storage: HardWorker
  src/core/HardWorker.sol
  src/interfaces/IHardWorker.sol
  test/core/Platform.Polygon.t.sol
Labels: ALPHA, refactoring

#32 UI getters
  src/core/Platform.sol
  src/core/VaultManager.sol
  src/interfaces/IAmmAdapter.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IVaultManager.sol
  test/core/Platform.Polygon.t.sol
  test/core/Platform.t.sol
Labels: enhancement, ALPHA

#42 Improve strategies coverage
  README.md
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  test/base/UniversalTest.sol
Labels: ALPHA, refactoring

#45 Update issue templates
  .github/ISSUE_TEMPLATE/adapter.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/strategy.md
  .github/ISSUE_TEMPLATE/vault.md
Labels: documentation, ALPHA

#41 bridge interfaces
  src/interfaces/IBridge.sol
  src/interfaces/IChildERC20.sol
  src/interfaces/IChildERC721.sol
  src/interfaces/IChildTokenFactory.sol
  src/interfaces/IInterChainAdapter.sol
Labels: BRIDGE

#39 2 namespaced storage
  script/libs/DeployLib.sol
  script/libs/DeployStrategyLib.sol
  src/core/AprOracle.sol
  src/core/Factory.sol
  src/core/Platform.sol
  src/core/PriceReader.sol
  src/core/StrategyLogic.sol
  src/core/Swapper.sol
  src/core/VaultManager.sol
  src/core/libs/FactoryLib.sol
  src/core/proxy/StrategyProxy.sol
  src/core/vaults/CVault.sol
  src/core/vaults/RMVault.sol
  src/core/vaults/RVault.sol
  src/interfaces/IFactory.sol
  src/interfaces/IPlatform.sol
  src/interfaces/ISwapper.sol
  src/interfaces/IVault.sol
  src/strategies/libs/StrategyLib.sol
  src/test/MockVaultUpgrade.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/Proxy.t.sol
  test/core/Swapper.Polygon.t.sol
  test/core/Vault.t.sol
Labels: ALPHA, refactoring

#40 Upgrade Storage
  src/core/base/RVaultBase.sol
  src/core/base/VaultBase.sol
  src/core/vaults/CVault.sol
  src/core/vaults/RMVault.sol
  src/core/vaults/RVault.sol
  src/interfaces/IRVault.sol
  src/interfaces/IVault.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/FarmingStrategyBase.sol
  src/strategies/base/LPStrategyBase.sol
  src/strategies/base/StrategyBase.sol
  src/test/MockStrategy.sol
  src/test/MockVaultUpgrade.sol
  test/core/Vault.t.sol
Labels: ALPHA, refactoring

#53 AMM adapters refactoring, full coverage, add getSpecificName to QSF
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/interfaces/IAmmAdapter.sol
  src/interfaces/ICAmmAdapter.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/libs/UniswapV3MathLib.sol
  src/test/MockAmmAdapter.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/adapters/KyberAdapter.Polygon.t.sol
  test/adapters/UniswapV3Adapter.Polygon.t.sol
  test/base/UniversalTest.sol
  test/core/Swapper.Polygon.t.sol
Labels: ALPHA, refactoring

#54 Fixing RMVault, getSpecificName,, AMM adapters refactoring, etc
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/VaultManager.sol
  src/core/libs/FactoryLib.sol
  src/core/vaults/RMVault.sol
  src/interfaces/IAmmAdapter.sol
  src/interfaces/ICAmmAdapter.sol
  src/interfaces/IStrategy.sol
  src/interfaces/IVaultManager.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/StrategyBase.sol
  src/test/MockAmmAdapter.sol
  src/test/MockStrategy.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/adapters/KyberAdapter.Polygon.t.sol
  test/adapters/UniswapV3Adapter.Polygon.t.sol
  test/core/Platform.Polygon.t.sol
  test/core/RMVault.Polygon.t.sol
Labels: enhancement, ALPHA, refactoring

#52 Upgrade VaultBase
  src/core/Platform.sol
  src/core/Zap.sol
  src/core/base/VaultBase.sol
  src/core/vaults/CVault.sol
  src/core/vaults/RMVault.sol
  src/core/vaults/RVault.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IVault.sol
  src/interfaces/IZap.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/StrategyLib.sol
  src/test/MockVaultUpgrade.sol
  test/base/UniversalTest.sol
  test/core/Platform.Polygon.t.sol
  test/core/Platform.t.sol
  test/core/RMVault.Polygon.t.sol
  test/core/Vault.t.sol
  test/core/VaultManager.t.sol
  test/core/VaultSharePrice.t.sol
  test/core/Zap.Polygon.t.sol
Labels: enhancement, ALPHA, refactoring

#55 Factory bugfix, Platform refactoring
  chains/PolygonLib.sol
  src/core/Factory.sol
  src/core/Platform.sol
  src/core/StrategyLogic.sol
  src/core/VaultManager.sol
  src/interfaces/IPlatform.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/StrategyLib.sol
  test/core/Platform.t.sol
Labels: bug, ALPHA, refactoring

#56 base strategy hooks, emit prices in HardWork event
  src/core/PriceReader.sol
  src/core/base/VaultBase.sol
  src/interfaces/IPriceReader.sol
  src/interfaces/IStrategy.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/StrategyLib.sol
  test/base/UniversalTest.sol
  test/core/PriceReader.t.sol
  test/core/VaultSharePrice.t.sol
Labels: enhancement, ALPHA

#46 mitigate vulns via refactoring & skip false positive alerts
  .gitignore
  slither.config.json
  src/adapters/AlgebraAdapter.sol
  src/adapters/ChainlinkAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/AprOracle.sol
  src/core/Factory.sol
  src/core/HardWorker.sol
  src/core/Platform.sol
  src/core/PriceReader.sol
  src/core/StrategyLogic.sol
  src/core/Swapper.sol
  src/core/VaultManager.sol
  src/core/Zap.sol
  src/core/base/Controllable.sol
  src/core/base/RVaultBase.sol
  src/core/base/UpgradeableProxy.sol
  src/core/base/VaultBase.sol
  src/core/libs/CommonLib.sol
  src/core/libs/FactoryLib.sol
  src/core/libs/RVaultLib.sol
  src/core/proxy/Proxy.sol
  src/core/proxy/StrategyProxy.sol
  src/core/proxy/VaultProxy.sol
  src/core/vaults/RMVault.sol
  src/core/vaults/RVault.sol
  src/interfaces/IControllable.sol
  src/interfaces/IFactory.sol
  src/interfaces/IHardWorker.sol
  src/interfaces/IPlatform.sol
  src/interfaces/IRVault.sol
  src/interfaces/IStrategy.sol
  src/interfaces/IStrategyProxy.sol
  src/interfaces/ISwapper.sol
  src/interfaces/IVault.sol
  src/interfaces/IVaultManager.sol
  src/interfaces/IVaultProxy.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/FarmingStrategyBase.sol
  src/strategies/base/LPStrategyBase.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/LPStrategyLib.sol
  src/strategies/libs/QuickswapLib.sol
  src/strategies/libs/StrategyLib.sol
  src/strategies/libs/UniswapV3MathLib.sol
  src/test/MockStrategy.sol
  src/test/MockVaultUpgrade.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Vault.t.sol
Labels: refactoring, SECURITY

#59 IStrategy.description
  src/interfaces/IStrategy.sol
  src/strategies/GammaQuickSwapFarmStrategy.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/libs/QuickswapLib.sol
  src/test/MockStrategy.sol
  test/base/UniversalTest.sol
Labels: enhancement, ALPHA, refactoring

#60 Platform: rebalancer, bridge, refactoring
  script/libs/DeployLib.sol
  src/core/Platform.sol
  src/interfaces/IPlatform.sol
  test/base/FullMockSetup.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/PriceReader.t.sol
Labels: ALPHA, refactoring

#61 RVaultBase decrease size, refactoring
  src/core/base/RVaultBase.sol
  src/core/base/VaultBase.sol
  src/core/libs/RVaultLib.sol
  src/interfaces/IRVault.sol
  src/interfaces/IVault.sol
Labels: ALPHA, refactoring

#65 QSF: decrease size
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/libs/QuickswapLib.sol
Labels: ALPHA
