Repository stabilitydao/stability-contracts, pull requests merged in 2023-12, with the labels that each got.

#69 23.12.0-alpha polygon deployment, doc fixes
  .env.example
  README.md
  audits/InitialAuditReport.md
  audits/README.md
  foundry.toml
Labels: documentation, ALPHA

#58 Add QSF custom test, improve coverage
  .gitignore
  src/integrations/algebra/IAlgebraEternalVirtualPool.sol
  src/integrations/algebra/IAlgebraVirtualPool.sol
  src/integrations/algebra/IAlgebraVirtualPoolBase.sol
  src/strategies/libs/StrategyLib.sol
  test/base/UniversalTest.sol
  test/core/PriceReader.t.sol
  test/core/RMVault.Polygon.t.sol
  test/strategies/GQF.Polygon.sol
  test/strategies/QSF.BonusReward.Polygon.t.sol
  test/strategies/QSF.Polygon.t.sol
Labels: BETA

#70 23.12.2-alpha
  chains/PolygonLib.sol
  script/PrepareUpgrade.23.12.2-alpha.Polygon.s.sol
  src/adapters/AlgebraAdapter.sol
  src/adapters/KyberAdapter.sol
  src/adapters/UniswapV3Adapter.sol
  src/core/Zap.sol
  src/core/libs/RVaultLib.sol
  src/core/proxy/StrategyProxy.sol
  src/core/proxy/VaultProxy.sol
  src/interfaces/ICAmmAdapter.sol
  src/interfaces/IStrategyProxy.sol
  src/interfaces/IVaultProxy.sol
  src/interfaces/IZap.sol
  src/strategies/QuickswapV3StaticFarmStrategy.sol
  src/strategies/base/StrategyBase.sol
  src/strategies/libs/LPStrategyLib.sol
  src/strategies/libs/QuickswapLib.sol
  src/test/MockStrategy.sol
  test/adapters/AlgebraAdapter.Polygon.t.sol
  test/adapters/KyberAdapter.Polygon.t.sol
  test/adapters/UniswapV3Adapter.Polygon.t.sol
  test/base/UniversalTest.sol
  test/core/Factory.t.sol
  test/core/Platform.t.sol
  test/core/Vault.t.sol
  test/core/Zap.Polygon.t.sol
  test/strategies/QSF.FarmingOutOfMoney.Polygon.t.sol
Labels: bug, enhancement, STRATEGY, refactoring, SECURITY, PLATFORM UPGRADE
